version: "3.9"

services:
  app:
    build: .
    image: otel-example-go:app-only
    container_name: otel-example-app
    environment:
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-appuser}
      - DB_PASSWORD=${DB_PASSWORD:-apppassword}
      - DB_NAME=${DB_NAME:-otel_example}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-otel-collector:4317}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-otel-example-api}
      - OTEL_ENABLE_METRICS=${OTEL_ENABLE_METRICS:-true}
      - OTEL_ENABLE_TRACING=${OTEL_ENABLE_TRACING:-true}
      - OTEL_ENABLE_LOGGING=${OTEL_ENABLE_LOGGING:-true}
    ports:
      - "8080:8080"
    depends_on: []
    command: ["/app"]


